import { expect, test, type Page } from "@playwright/test";

import {
  clearTerminalReportFailure,
  restoreReportAlertRead,
  restoreReportRead,
  revokeReportAlertRead,
  revokeReportRead,
  seedTerminalReportFailure,
} from "@/tests/support/scheduled-report";
import { runSql } from "@/tests/support/database";
import { expectLandsOn, fixtures, openNavigation, signIn } from "./fixtures";

/**
 * Reading yesterday's report, on a phone, a tablet and a desktop (product.md §18, design.md §3.5).
 *
 * The report itself was generated by `e2e/global-setup.ts` the only way anything can generate one:
 * by running the private 00:01 function as the database role that owns the Cron job. There is no
 * button on any screen that produces a report, and these tests would be lying if they made one.
 *
 * WHAT IS BEING PROVEN, beyond "the page renders":
 *
 *   · A Director and the Manager both reach it, and a Cashier reaches neither the destination nor
 *     the address behind it.
 *   · The integrity finding is stated on the screen, because a snapshot whose digest no longer
 *     matches is a thing a Director must be told about rather than a thing a log records.
 *   · A till nobody counted says so IN WORDS. The single most damaging thing this screen could do
 *     is render a missing count as a zero (§15.2a), so the phone tier checks it directly.
 *
 *   · A FAILED READ IS A STATED FAILURE, not an empty archive (§12.7 rule 7). The read that fails
 *     runs between the Next server and Postgres, so it is broken WHERE IT REALLY BREAKS: the grant
 *     on `public.daily_reports` is taken away for the length of one navigation. Aborting the
 *     browser's own request would exercise the router's transport fallback and report a pass for
 *     something else entirely, and a fault switch inside the application would be a production back
 *     door kept alive by a test.
 *   · On a phone the seventeen sections start collapsed under a summary, and open when pressed.
 */
const REPORTS_HEADING = /daily reports/i;

/**
 * Signs in and goes straight to the archive.
 *
 * `expectLandsOn` is not decoration: `submitPassword` returns the moment the click lands, and a
 * `goto` issued before the sign-in navigation finishes cancels it — the session cookie is never
 * written and the test is quietly exercising the signed-out path.
 */
async function openReports(page: Page, who: { phone: string; password: string }) {
  await signIn(page, who.phone, who.password);
  await expectLandsOn(page, "/dashboard");

  await page.goto("/reports");
  await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible();
}

/**
 * Opens one report section if this tier starts it shut.
 *
 * A phone opens the report as a summary with the sections collapsed; a tablet and a desktop have
 * room and start them open. A test that clicked unconditionally would OPEN one tier and CLOSE the
 * other two, so it asks the control what it is before pressing it.
 */
async function openSection(page: Page, key: string) {
  const toggle = page.getByTestId(`report-toggle-${key}`);
  if ((await toggle.getAttribute("aria-expanded")) === "false") await toggle.click();
  await expect(toggle).toHaveAttribute("aria-expanded", "true");
}

/** The newest card in the archive, opened. */
async function openNewestReport(page: Page) {
  await page.locator("[data-testid^='report-']").first().click();
  await expect(page.getByRole("heading", { name: /report for /i })).toBeVisible();
}

test("a Director reaches the reports from the navigation and reads one", async ({
  page,
}, testInfo) => {
  const { director } = fixtures();
  await signIn(page, director.phone, director.password);
  await expectLandsOn(page, "/dashboard");

  const navigation = await openNavigation(page, testInfo);
  await navigation.getByRole("link", { name: REPORTS_HEADING }).click();

  await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible();

  // One card per business day. The archive is never empty here: global setup generated yesterday.
  const first = page.locator("[data-testid^='report-']").first();
  await expect(first).toBeVisible();
  await first.click();

  await expect(page.getByRole("heading", { name: /report for /i })).toBeVisible();
  await expect(page).toHaveURL(/\/reports\/[0-9a-f-]{36}/);
});

test("the report states its own integrity, with the fingerprint it was checked against", async ({
  page,
}) => {
  await openReports(page, fixtures().director);
  await openNewestReport(page);

  const integrity = page.getByRole("region", { name: /integrity check/i });
  await expect(integrity).toBeVisible();
  await expect(integrity.getByText(/^checked$/i)).toBeVisible();
  await expect(integrity.getByText(/still matches the fingerprint/i)).toBeVisible();
  // A full SHA-256, shown so it can be quoted.
  await expect(integrity.getByText(/[0-9a-f]{64}/)).toBeVisible();
});

test("the report names who received it, by role", async ({ page }) => {
  await openReports(page, fixtures().director);

  // §13.1 asks the list to lead with delivery; §7.21 asks the report to show it.
  await expect(page.getByText(/delivered to \d+/i).first()).toBeVisible();

  await openNewestReport(page);

  const delivery = page.getByRole("region", { name: /^delivery$/i });
  await expect(delivery).toBeVisible();
  await expect(delivery.getByText(/in the app only/i)).toBeVisible();
  await expect(delivery.getByText(/E2E Director/)).toBeVisible();
  await expect(delivery.getByText(/E2E Manager/)).toBeVisible();
  // §18.1 names two roles and no others; nobody else can appear here.
  await expect(delivery.getByText(/E2E Cashier|E2E Sales Rep/)).toHaveCount(0);
});

test("a count nobody took is shown as words, never as a zero", async ({ page }) => {
  await openReports(page, fixtures().director);
  await openNewestReport(page);

  const till = page.getByRole("region", { name: /cashier's cash count/i });
  await expect(till).toBeVisible();

  // The chip is on the heading, so it is readable before the section is opened at all.
  await expect(till.getByText(/^not counted$/i)).toBeVisible();

  await openSection(page, "cashierReconciliation");
  await expect(till.getByText(/nobody counted the till/i)).toBeVisible();

  // The three figures are absent, and each says so. `TZS 0` anywhere in this card would mean the
  // screen had told a Director the till balanced on a night nobody opened it.
  await expect(till.getByText(/not recorded/i)).toHaveCount(3);
  await expect(till.getByText(/TZS/)).toHaveCount(0);
});

/**
 * Issue #51 · Imprest spending does not exist on main, so its figures are WITHHELD — a different
 * fact from "not recorded", worded differently and explained, and never a zero or a balance.
 */
test("imprest figures the system cannot give yet say so, and are never a zero", async ({ page }) => {
  await openReports(page, fixtures().director);
  await openNewestReport(page);

  const balance = page.getByRole("region", { name: /imprest balance/i });
  await openSection(page, "imprestPosition");
  await expect(balance.getByText(/^not available$/i)).toHaveCount(4);
  await expect(balance.getByText(/imprest spending is not in the system yet/i)).toBeVisible();
  await expect(balance.getByText(/TZS/)).toHaveCount(0);

  const expenses = page.getByRole("region", { name: /approved imprest expenses/i });
  await openSection(page, "imprestExpenses");
  await expect(expenses.getByText(/^not available$/i)).toHaveCount(2);
  await expect(expenses.getByText(/TZS/)).toHaveCount(0);
});

test("every approved section is on the page, whether or not it has figures", async ({ page }) => {
  await openReports(page, fixtures().director);
  await openNewestReport(page);

  for (const heading of [
    /^sales$/i,
    /^invoices$/i,
    /payments by method/i,
    /outstanding credit/i,
    /discounts and approvals/i,
    /paid, not yet handed over/i,
    /stock released/i,
    /stock corrections/i,
    /supplier shortages/i,
    /production batches/i,
    /bricks made and rejected/i,
    /cashier's cash count/i,
    /waiting for a decision/i,
    /imprest funding/i,
    /approved imprest expenses/i,
    /imprest balance/i,
    /imprest cash count/i,
  ]) {
    await expect(page.getByRole("heading", { name: heading })).toBeVisible();
  }
});

test("the Manager reads the same report", async ({ page }, testInfo) => {
  const { manager } = fixtures();
  await signIn(page, manager.phone, manager.password);
  await expectLandsOn(page, "/dashboard");

  const navigation = await openNavigation(page, testInfo);
  await expect(navigation.getByRole("link", { name: REPORTS_HEADING })).toBeVisible();

  await page.goto("/reports");
  await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible();
  await openNewestReport(page);
});

test("the archive shows a skeleton shaped like it before the reports arrive", async ({
  page,
}, testInfo) => {
  const { director } = fixtures();
  await signIn(page, director.phone, director.password);
  await expectLandsOn(page, "/dashboard");

  // The prefetch is let through and the real navigation is slowed. Delaying everything would slow
  // the prefetch instead, and the click would then be served from a cache that arrived late — which
  // proves nothing about what a person sees while they wait.
  let seen = 0;
  await page.route(/\/reports/, async (route) => {
    seen += 1;
    if (seen > 1) await new Promise((resolve) => setTimeout(resolve, 3000));
    await route.continue();
  });

  const navigation = await openNavigation(page, testInfo);
  // `noWaitAfter`, because the click otherwise returns only once the navigation has settled — and
  // by then the skeleton this test exists to see has already been replaced by the page.
  await navigation.getByRole("link", { name: REPORTS_HEADING }).click({ noWaitAfter: true });

  const skeleton = page.getByRole("status");
  await expect(skeleton).toBeVisible({ timeout: 5000 });
  await expect(skeleton).toContainText(/working/i);

  // Shaped like the archive it stands in for: a card per day, and each card carrying the five
  // things a loaded card carries — the business date, how many people it reached, when it was
  // written, the integrity chip and the word that opens it (design.md §12.7 rule 3). A skeleton
  // promising fewer is a page that jumps as the rest arrives.
  const cards = skeleton.getByTestId("report-card-skeleton");
  await expect(cards).toHaveCount(5);
  for (const card of await cards.all()) {
    await expect(card.locator("[data-slot='skeleton']")).toHaveCount(5);
  }

  await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible({
    timeout: 20_000,
  });
});

test("a read the database refuses is stated as a failure, and the retry re-runs it", async ({
  page,
}) => {
  const { director } = fixtures();
  await signIn(page, director.phone, director.password);
  await expectLandsOn(page, "/dashboard");

  // The archive is there and readable, so what follows is a failure and not an empty night.
  await page.goto("/reports");
  await expect(page.locator("[data-testid^='report-']").first()).toBeVisible();

  try {
    revokeReportRead();
    await page.goto("/reports");

    // §12.5's third kind of error: page-level, because there is no content to attach it to.
    const alert = page
      .getByRole("alert")
      .filter({ has: page.getByRole("button", { name: /try again/i }) });
    await expect(alert).toBeVisible();
    await expect(alert).toContainText(/the system could not be reached/i);
    await expect(alert).toContainText(/nothing you did was lost, and nothing was changed/i);
    await expect(page.getByRole("heading", { name: /could not be loaded/i })).toBeVisible();

    // THE ASSERTION THIS TEST EXISTS FOR. "No report has been written yet" during an outage would
    // tell a Director the business produced nothing last night. There is also no half-page: the
    // archive's own heading and its cards are gone, not merely empty.
    await expect(page.getByText(/no report has been written yet/i)).toHaveCount(0);
    await expect(page.locator("[data-testid^='report-']")).toHaveCount(0);
  } finally {
    // Whatever happened above, the next test meets a working database.
    restoreReportRead();
  }

  // A retry re-runs the read that failed, rather than clearing the message and showing the same
  // dead page (§12.7 rule 7). The database answers again, so the archive comes back.
  await page.getByRole("button", { name: /try again/i }).click();
  await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible({
    timeout: 20_000,
  });
  await expect(page.locator("[data-testid^='report-']").first()).toBeVisible();
});

test("on a phone the report opens as a summary with its sections shut", async ({ page }) => {
  await openReports(page, fixtures().director);
  await openNewestReport(page);

  const overview = page.getByRole("region", { name: /at a glance/i });
  await expect(overview).toBeVisible();
  // It names what is unresolved rather than counting it, so the reader is not sent hunting.
  await expect(overview).toContainText(/still unresolved/i);

  const body = page.locator("#report-section-sales");
  const toggle = page.getByTestId("report-toggle-sales");

  // A phone is below `md`, so the sections start shut; a tablet and a desktop are above it and
  // start open. One markup, one CSS rule, three tiers.
  const phone = test.info().project.name === "mobile";
  await expect(body).toBeVisible({ visible: !phone });
  await expect(toggle).toHaveAttribute("aria-expanded", phone ? "false" : "true");

  // Shut or open, an unresolved count is legible without pressing anything (§18.2a).
  await expect(page.getByTestId("report-toggle-cashierReconciliation")).toContainText(
    /not counted/i,
  );

  await toggle.click();
  await expect(body).toBeVisible({ visible: phone });
  await expect(toggle).toHaveAttribute("aria-expanded", phone ? "true" : "false");
});

test("a Cashier is offered no reports and refused the address", async ({ page }, testInfo) => {
  const { cashier } = fixtures();
  await signIn(page, cashier.phone, cashier.password);
  await expectLandsOn(page, "/payments");

  // Nothing in the interface offers it — no greyed entry, no tooltip (design.md §4.3).
  const navigation = await openNavigation(page, testInfo);
  await expect(navigation.getByRole("link", { name: REPORTS_HEADING })).toHaveCount(0);

  await page.goto("/reports");
  await expect(page).toHaveURL(/\/no-access/);
  await expect(page.getByRole("heading", { name: /don't have access/i })).toBeVisible();

  // And the detail address is refused too, rather than only the list it is reached from.
  await page.goto("/reports/00000000-0000-0000-0000-000000000000");
  await expect(page).toHaveURL(/\/no-access/);
});

/**
 * Issue #19 · a night that produced no report at all, seen on all three tiers.
 *
 * The failure is seeded against an older business date because the one the scheduler is on already
 * has a report — global setup generated it — and a business date cannot be both reported and
 * terminally failed. `seedTerminalReportFailure` writes the terminal run from the operator's psql
 * prompt and then calls the database's own alert function, so the alert, its deduplication and its
 * audit row are all real. How a night REACHES terminal is driven for real in
 * `017_scheduled_report_retries.sql`; what these tests own is what a person sees.
 */
const FAILED_NIGHT = "2026-02-11";

test("a night with no report is stated at the top of the archive, on every tier", async ({
  page,
}) => {
  seedTerminalReportFailure(FAILED_NIGHT);

  try {
    await openReports(page, fixtures().director);

    const alert = page.getByTestId("missing-report-alerts");
    await expect(alert).toBeVisible();

    // WORDS AND A SHAPE, not only a colour (design.md §11.5). The heading says what happened, the
    // entry names the night, and a triangle carries the same meaning to a reader who cannot
    // separate red from the page.
    await expect(alert).toContainText(/report not written/i);
    await expect(alert).toContainText(/high priority/i);
    await expect(alert.locator("svg")).toHaveCount(1);
    await expect(page.getByTestId(`missing-report-alert-${FAILED_NIGHT}`)).toContainText(
      /11 February 2026/i,
    );
    await expect(alert).toContainText(/every attempt failed/i);

    // IT IS ABOVE THE ARCHIVE, on a phone as much as on a desktop. A missing night has no card, so
    // a reader scanning the list below would find the date simply absent.
    const alertBox = await alert.boundingBox();
    const firstCard = await page.locator("[data-testid^='report-']").first().boundingBox();
    expect(alertBox!.y).toBeLessThan(firstCard!.y);

    // AND THERE IS NOTHING TO PRESS. Issue #19 adds no retry and no dismissal, and a control that
    // looked like one would tell a Director they had fixed a night that is still missing.
    await expect(alert.getByRole("button")).toHaveCount(0);
    await expect(alert.getByRole("link")).toHaveCount(0);

    // IT ANNOUNCES ASSERTIVELY, which is this project's semantics for a failure — the same
    // `role="alert"` that `FormError` and the shell's error boundary carry, rather than the polite
    // `role="status"` a loading skeleton uses. A reader who cannot see the page should not have to
    // find, by exploration, that the business has no record of a day's trading.
    await expect(alert).toHaveAttribute("role", "alert");
  } finally {
    clearTerminalReportFailure(FAILED_NIGHT);
  }
});

test("one alert per night, however many times the last slot was delivered", async ({ page }) => {
  seedTerminalReportFailure(FAILED_NIGHT);

  try {
    // The database refuses a second alert for the same night; the screen must therefore show one
    // entry, not two identical warnings stacked on a phone.
    await openReports(page, fixtures().director);

    await expect(page.getByTestId(`missing-report-alert-${FAILED_NIGHT}`)).toHaveCount(1);
    await expect(page.getByTestId("missing-report-alerts").getByRole("listitem")).toHaveCount(1);
  } finally {
    clearTerminalReportFailure(FAILED_NIGHT);
  }
});

test("a failed alert read is a page-level failure, not a page with no warnings on it", async ({
  page,
}) => {
  seedTerminalReportFailure(FAILED_NIGHT);

  try {
    await openReports(page, fixtures().director);
    await expect(page.getByTestId("missing-report-alerts")).toBeVisible();

    revokeReportAlertRead();
    await page.goto("/reports");

    const failure = page
      .getByRole("alert")
      .filter({ has: page.getByRole("button", { name: /try again/i }) });
    await expect(failure).toBeVisible();
    await expect(failure).toContainText(/the system could not be reached/i);

    // THE ASSERTION THIS TEST EXISTS FOR. A page that rendered the archive with no alert region
    // would tell a Director every night has its report — during the one outage in which nobody can
    // find out. The archive is gone too, not merely quiet.
    await expect(page.getByTestId("missing-report-alerts")).toHaveCount(0);
    await expect(page.locator("[data-testid^='report-']")).toHaveCount(0);

    restoreReportAlertRead();

    // The retry re-runs the read that failed rather than clearing the message (§12.7 rule 7), and
    // the warning comes back with it.
    await page.getByRole("button", { name: /try again/i }).click();
    await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible({
      timeout: 20_000,
    });
    await expect(page.getByTestId("missing-report-alerts")).toBeVisible();
  } finally {
    restoreReportAlertRead();
    clearTerminalReportFailure(FAILED_NIGHT);
  }
});

test("the Manager is warned too, and a Cashier is refused the address entirely", async ({
  page,
}) => {
  seedTerminalReportFailure(FAILED_NIGHT);

  try {
    const { manager, cashier } = fixtures();

    await openReports(page, manager);
    await expect(page.getByTestId(`missing-report-alert-${FAILED_NIGHT}`)).toBeVisible();

    await page.context().clearCookies();
    await signIn(page, cashier.phone, cashier.password);
    await expectLandsOn(page, "/payments");

    // Refused at the route, and the alert is behind it. A Cashier is not shown a warning about a
    // report they may not read.
    await page.goto("/reports");
    await expect(page).toHaveURL(/\/no-access/);
    await expect(page.getByTestId("missing-report-alerts")).toHaveCount(0);
  } finally {
    clearTerminalReportFailure(FAILED_NIGHT);
  }
});

test("the archive shows no warning on a night that has its report", async ({ page }) => {
  await openReports(page, fixtures().director);

  // Nothing was seeded, and every night in the archive was generated, so there is no unresolved
  // failure to state. An empty alert region would be noise on every ordinary morning.
  await expect(page.getByTestId("missing-report-alerts")).toHaveCount(0);
  await expect(page.locator("[data-testid^='report-']").first()).toBeVisible();
});

/**
 * Issue #19, F4 · Try again is pending until the refresh it started actually settles (§12.7).
 *
 * `retry()` returns at once, and the refreshed server content arrives later. Here the refresh is
 * HELD at the network: every non-prefetch RSC request for `/reports` waits until the test releases
 * it, so "pending" is observed for as long as the refresh is really unanswered, not for however
 * long a fast local server happens to take. The read fails where it really fails, with the grant on
 * the alert view withdrawn, and recovers when the grant comes back.
 */
test("Try again stays pending and single until the held refresh settles, then fails again or recovers", async ({
  page,
}) => {
  seedTerminalReportFailure(FAILED_NIGHT);

  const held: Array<() => void> = [];
  let refreshes = 0;

  try {
    await openReports(page, fixtures().director);
    await expect(page.getByTestId("missing-report-alerts")).toBeVisible();

    revokeReportAlertRead();
    await page.goto("/reports");

    // By its message, not by the button's name: the button is renamed while it is pending.
    const failure = page
      .getByRole("alert")
      .filter({ hasText: /the system could not be reached/i });
    await expect(failure).toBeVisible();

    // By its slot inside the failure, not by name: a pending Button is announced as "Working…", so
    // a name-based locator would stop matching exactly when the pending state is being asserted.
    const retry = failure.locator("button[data-slot='button']");
    await expect(retry).toHaveAccessibleName(/try again/i);
    const before = await retry.boundingBox();
    expect(before).not.toBeNull();

    await page.route(
      (url) => url.pathname === "/reports",
      async (route, request) => {
        const headers = request.headers();
        if (request.method() !== "GET" || headers["rsc"] !== "1" || headers["next-router-prefetch"]) {
          return route.continue();
        }
        refreshes += 1;
        await new Promise<void>((release) => held.push(release));
        await route.continue().catch(() => {});
      },
    );

    // FIRST ATTEMPT: pending at once, the same size, and announced for what it is doing.
    await retry.click();
    await expect.poll(() => held.length).toBe(1);
    await expect(retry).toHaveAttribute("aria-busy", "true");
    await expect(retry).toBeDisabled();
    await expect(retry).toHaveAccessibleName(/working/i);
    const during = await retry.boundingBox();
    expect(Math.abs(during!.width - before!.width)).toBeLessThan(0.5);
    expect(Math.abs(during!.height - before!.height)).toBeLessThan(0.5);

    // Pressed again while the refresh is held: nothing new is requested.
    const centre = { x: during!.x + during!.width / 2, y: during!.y + during!.height / 2 };
    await page.mouse.click(centre.x, centre.y);
    await page.mouse.click(centre.x, centre.y);
    await page.waitForTimeout(500);
    expect(refreshes).toBe(1);
    await expect(retry).toHaveAttribute("aria-busy", "true");

    // The held refresh is answered, and the read is still refused: the failure stays, and the
    // control is live again for a fresh, deliberate retry.
    held[0]!();
    await expect(retry).not.toHaveAttribute("aria-busy", "true");
    await expect(retry).toBeEnabled();
    await expect(retry).toHaveAccessibleName(/try again/i);
    await expect(failure).toContainText(/the system could not be reached/i);
    await expect(page.getByTestId("missing-report-alerts")).toHaveCount(0);

    // SECOND ATTEMPT: guarded in the same way, and this time the database answers.
    await retry.click();
    await expect.poll(() => held.length).toBe(2);
    await expect(retry).toHaveAttribute("aria-busy", "true");
    await expect(retry).toBeDisabled();
    expect(refreshes).toBe(2);

    restoreReportAlertRead();
    held[1]!();

    await expect(page.getByRole("heading", { name: REPORTS_HEADING })).toBeVisible({
      timeout: 20_000,
    });
    await expect(page.getByTestId(`missing-report-alert-${FAILED_NIGHT}`)).toBeVisible();
    await expect(failure).toHaveCount(0);
    expect(refreshes).toBe(2);
  } finally {
    for (const release of held) release();
    await page.unrouteAll({ behavior: "ignoreErrors" });
    restoreReportAlertRead();
    clearTerminalReportFailure(FAILED_NIGHT);
  }
});

/**
 * Issue #51 · The same F4 guard on a route that is NOT a report.
 *
 * `app/(app)/error.tsx` is the shell's one error boundary, so the pending retry changes every screen
 * under it, not only the report archive. This proves it on the imprest funding screen: the read is
 * refused where it really fails (the grant on `imprest_funding_position` is withdrawn, as
 * `imprest-funding.spec.ts` already does), the refresh is held at the network, and the control stays
 * pending, the same size and single until that refresh settles.
 */
test("Try again on a non-report screen is pending and single until its held refresh settles", async ({
  page,
}) => {
  const held: Array<() => void> = [];
  let refreshes = 0;

  try {
    const { director } = fixtures();
    await signIn(page, director.phone, director.password);
    await expectLandsOn(page, "/dashboard");

    runSql("revoke select on public.imprest_funding_position from authenticated;");
    await page.goto("/imprest");

    const failure = page
      .getByRole("alert")
      .filter({ hasText: /the system could not be reached/i });
    await expect(failure).toBeVisible();
    const retry = failure.locator("button[data-slot='button']");
    await expect(retry).toHaveAccessibleName(/try again/i);
    const before = await retry.boundingBox();
    expect(before).not.toBeNull();

    await page.route(
      (url) => url.pathname === "/imprest",
      async (route, request) => {
        const headers = request.headers();
        if (request.method() !== "GET" || headers["rsc"] !== "1" || headers["next-router-prefetch"]) {
          return route.continue();
        }
        refreshes += 1;
        await new Promise<void>((release) => held.push(release));
        await route.continue().catch(() => {});
      },
    );

    await retry.click();
    await expect.poll(() => held.length).toBe(1);
    await expect(retry).toHaveAttribute("aria-busy", "true");
    await expect(retry).toBeDisabled();
    const during = await retry.boundingBox();
    expect(Math.abs(during!.width - before!.width)).toBeLessThan(0.5);
    expect(Math.abs(during!.height - before!.height)).toBeLessThan(0.5);

    const centre = { x: during!.x + during!.width / 2, y: during!.y + during!.height / 2 };
    await page.mouse.click(centre.x, centre.y);
    await page.waitForTimeout(500);
    expect(refreshes).toBe(1);

    // Still refused: the failure stays and the control is live for a deliberate retry.
    held[0]!();
    await expect(retry).toBeEnabled();
    await expect(retry).toHaveAccessibleName(/try again/i);
    await expect(failure).toBeVisible();

    // Restored: the next retry recovers the screen itself.
    runSql("grant select on public.imprest_funding_position to authenticated;");
    await retry.click();
    await expect.poll(() => held.length).toBe(2);
    held[1]!();
    await expect(page.getByRole("heading", { name: /imprest funding/i }).first()).toBeVisible({
      timeout: 20_000,
    });
    await expect(failure).toHaveCount(0);
  } finally {
    for (const release of held) release();
    await page.unrouteAll({ behavior: "ignoreErrors" });
    runSql("grant select on public.imprest_funding_position to authenticated;");
  }
});
